# Generated by Django 4.0.6 on 2022-11-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descriprtion',
            new_name='description',
        ),
    ]
