# Generated by Django 4.0.6 on 2022-11-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_rename_descriprtion_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
